// php-laravel/resources/js/components/Similar.tsx
import { Link } from '@inertiajs/react';
import { Image } from './Image';

export function Similar({ data }: any) {
    return (
        <div>
            <h3>You might also like</h3>
            <div className="flex flex-row gap-2 overflow-auto">
                {data.moreLikeThisTitles.edges.map((edge: any) => (
                    <Link
                        key={edge?.node?.id}
                        href={`/inertia/${edge?.node?.id}`}
                        className="flex w-[130px] shrink-0 flex-col content-start justify-start overflow-hidden grayscale transition-all hover:grayscale-0"
                    >
                        <Image
                            src={edge.node?.primaryImage?.url}
                            alt={edge?.node?.titleText?.text}
                            className="aspect-[10/16] w-[130px] rounded-sm"
                        />
                        <div className="p-1">
                            <p className="text-xs opacity-50">
                                {edge?.node?.titleType?.text} ∙{' '}
                                {edge?.node?.releaseYear?.year}
                            </p>
                            <p className="truncate text-sm">
                                {edge?.node?.titleText?.text}
                            </p>
                        </div>
                    </Link>
                ))}
            </div>
        </div>
    );
}

export function SimilarSkeleton() {
    return (
        <div>
            <h3>You might also like</h3>
            <div className="flex flex-row gap-2 overflow-auto">
                {[0, 1].map((i) => (
                    <div
                        key={i}
                        className="flex w-[130px] shrink-0 flex-col content-start justify-start overflow-hidden"
                    >
                        <div className="flex aspect-[10/16] w-full shrink-0 animate-pulse rounded-sm bg-[#222]" />
                        <div className="flex flex-col gap-1 p-1">
                            <div className="flex h-[.9lh] w-[80%] animate-pulse rounded-md bg-[#222]" />
                            <div className="flex h-[.84lh] w-[60%] animate-pulse rounded-md bg-[#222]" />
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}

// nodejs-vue/src/components/Similar.tsx
/** @jsxImportSource vue */

import { defineComponent } from "vue";

import { fetchSimilar } from "../api/similar.ts";
import { Image } from "./Image.tsx";

const TYPES = {
  movie: "Movie",
  tvSeries: "TV Series",
  tvEpisode: "TV Episode",
  tvMovie: "TV Movie",
  tvShort: "TV Short",
  tvSpecial: "TV Special",
};

export const Similar = defineComponent({
  name: "Similar",
  props: {
    id: {
      type: String,
      required: true,
    },
  },
  async setup(props) {
    const data = await fetchSimilar({ id: props.id });

    return () => (
      <section>
        <h3>You might also like</h3>
        <div class="flex flex-row gap-2 overflow-auto">
          {data.similarTitles.map((title: any) => (
            <a
              key={title?.id}
              href={`?id=${title?.id}`}
              class="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden grayscale hover:grayscale-0 transition-all"
            >
              <Image
                src={title?.primaryImage?.url}
                alt={title?.primaryTitle}
                className="w-[130px] aspect-[10/16] rounded-sm"
              />
              <div class="p-1">
                <p class="opacity-50 text-xs">
                  {TYPES[title?.type as keyof typeof TYPES] || "Movie"} ∙{" "}
                  {title?.startYear}
                </p>
                <p class="truncate text-sm">{title?.primaryTitle}</p>
              </div>
            </a>
          ))}
        </div>
      </section>
    );
  },
});

export function SimilarSkeleton() {
  return (
    <section>
      <h3>You might also like</h3>
      <div class="flex flex-row gap-2 overflow-auto">
        {[0, 1].map((i) => (
          <div
            key={i}
            class="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden"
          >
            <div class="flex w-full shrink-0 aspect-[10/16] rounded-md bg-[#333] animate-pulse" />
            <div class="flex flex-col p-1 gap-1">
              <div class="flex h-[.9lh] w-[80%] rounded-md bg-[#333] animate-pulse" />
              <div class="flex h-[.84lh] w-[60%] rounded-md bg-[#333] animate-pulse" />
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
