// nodejs/src/components/Similar.tsx
import { fetchSimilar } from "../api/similar.ts";
import { Image } from "./Image.tsx";

export async function Similar({ id }: { id: string }) {
  const data = await fetchSimilar({ id });

  return (
    <div>
      <h3>You might also like</h3>
      <div className="flex flex-row gap-2 overflow-auto">
        {data.moreLikeThisTitles.edges.map((edge: any) => (
          <a
            key={edge?.node?.id}
            href={`?id=${edge?.node?.id}`}
            className="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden grayscale hover:grayscale-0 transition-all"
          >
            <Image
              src={edge.node?.primaryImage?.url}
              alt={edge?.node?.titleText?.text}
              className="w-[130px] aspect-[10/16] rounded-sm"
            />
            <div className="p-1">
              <p className="opacity-50 text-xs">
                {edge?.node?.titleType?.text} ∙ {edge?.node?.releaseYear?.year}
              </p>
              <p className="truncate text-sm">{edge?.node?.titleText?.text}</p>
              </div>
          </a>
        ))}
      </div>
    </div>
  );
}

export function SimilarSkeleton() {
  return (
    <div>
      <h3>You might also like</h3>
      <div className="flex flex-row gap-2 overflow-auto">
        {[0, 1].map((i) => (
          <div
            key={i}
            className="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden"
          >
            <div className="flex w-full shrink-0 aspect-[10/16] rounded-sm bg-[#222] animate-pulse" />
            <div className="flex flex-col p-1 gap-1">
              <div className="flex h-[.9lh] w-[80%] rounded-md bg-[#222] animate-pulse" />
              <div className="flex h-[.84lh] w-[60%] rounded-md bg-[#222] animate-pulse" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// nodejs-vue/src/components/Similar.tsx
/** @jsxImportSource vue */

import { defineComponent } from "vue";

import { fetchSimilar } from "../api/similar.ts";
import { Image } from "./Image.tsx";

const TYPES = {
  movie: "Movie",
  tvSeries: "TV Series",
  tvEpisode: "TV Episode",
  tvMovie: "TV Movie",
  tvShort: "TV Short",
  tvSpecial: "TV Special",
};

export const Similar = defineComponent({
  name: "Similar",
  props: {
    id: {
      type: String,
      required: true,
    },
  },
  async setup(props) {
    const data = await fetchSimilar({ id: props.id });

    return () => (
      <section>
        <h3>You might also like</h3>
        <div class="flex flex-row gap-2 overflow-auto">
          {data.similarTitles.map((title: any) => (
            <a
              key={title?.id}
              href={`?id=${title?.id}`}
              class="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden grayscale hover:grayscale-0 transition-all"
            >
              <Image
                src={title?.primaryImage?.url}
                alt={title?.primaryTitle}
                className="w-[130px] aspect-[10/16] rounded-sm"
              />
              <div class="p-1">
                <p class="opacity-50 text-xs">
                  {TYPES[title?.type as keyof typeof TYPES] || "Movie"} ∙{" "}
                  {title?.startYear}
                </p>
                <p class="truncate text-sm">{title?.primaryTitle}</p>
              </div>
            </a>
          ))}
        </div>
      </section>
    );
  },
});

export function SimilarSkeleton() {
  return (
    <section>
      <h3>You might also like</h3>
      <div class="flex flex-row gap-2 overflow-auto">
        {[0, 1].map((i) => (
          <div
            key={i}
            class="flex flex-col content-start justify-start shrink-0 w-[130px] overflow-hidden"
          >
            <div class="flex w-full shrink-0 aspect-[10/16] rounded-md bg-[#333] animate-pulse" />
            <div class="flex flex-col p-1 gap-1">
              <div class="flex h-[.9lh] w-[80%] rounded-md bg-[#333] animate-pulse" />
              <div class="flex h-[.84lh] w-[60%] rounded-md bg-[#333] animate-pulse" />
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
